
package View;

import java.awt.CardLayout;
import java.awt.event.*;

/**
 *
 * @author Muhammad Tsaqif Ammar
 */
public class App extends javax.swing.JFrame {
    
    private CardLayout cardLayout;
    private Login login;
    private Register register;
    private BerandaHotel berandaHotel;
    private MenuKamar menuKamar;
    private CustomerHotel customerHotel;
    private SettingsHotel settingsHotel;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        login = new Login();
        register = new Register();
        berandaHotel = new BerandaHotel();
        customerHotel = new CustomerHotel();
        menuKamar = new MenuKamar();
        settingsHotel = new SettingsHotel();
        
        cardLayout = (CardLayout) parentPanel.getLayout();
        parentPanel.add(login, "Login");
        parentPanel.add(register, "Register");
        parentPanel.add(berandaHotel, "BerandaHotel");
        parentPanel.add(customerHotel, "CustomerHotel");
        parentPanel.add(menuKamar, "MenuKamar");
        
        pack();
        
        routeLoginPage();
        routeRegisterPage();
        routeBerandaHotelPage();
        routeCustomerHotelPage();
        routeMenuKamarPage();
        routeSettingsHotelPage();
        
        cardLayout.show(parentPanel, "Login");
    }
    
    private void routeLoginPage() {
        login.getLabelAkun().addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                cardLayout.show(parentPanel, "Register");
            }
        });
        login.getButtonSubmit().addActionListener((ActionEvent e) -> {
            login.verifyInputUser();
        });
    }
    
    private void routeRegisterPage() {
        register.getLabelAkun().addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                cardLayout.show(parentPanel, "Login");
            }
        });
    }
    
    private void routeBerandaHotelPage() {
        berandaHotel.getButtonMenuKamar().addActionListener((ActionEvent e) -> {
            cardLayout.show(parentPanel, "MenuKamar");
        });
        berandaHotel.getButtonLihatCustomer().addActionListener((ActionEvent e) -> {
            cardLayout.show(parentPanel, "CustomerHotel");
        });
        berandaHotel.getButtonSettings().addActionListener((ActionEvent e) -> {
            cardLayout.show(parentPanel, "SettingsHotel");
        });
        berandaHotel.getButtonLogout().addActionListener((ActionEvent e) -> {
            cardLayout.show(parentPanel, "Login");
        });
    }
    
    private void routeCustomerHotelPage() {
        customerHotel.getLabelBack().addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                cardLayout.show(parentPanel, "BerandaHotel");
            }
        });
    }
    
    private void routeMenuKamarPage() {
        menuKamar.getLabelBack().addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                cardLayout.show(parentPanel, "BerandaHotel");
            }
        });
    }
    
    private void routeSettingsHotelPage() {
        settingsHotel.getLabelBack().addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                cardLayout.show(parentPanel, "BerandaHotel");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel parentPanel;
    // End of variables declaration//GEN-END:variables
}
