/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author asus
 */
public class BerandaHotel extends javax.swing.JPanel {

    /**
     * Creates new form BerandaHotel
     */
    public BerandaHotel() {
        initComponents();
    }

    public JButton getButtonLihatCustomer() {
        return buttonLihatCustomer;
    }

    public JButton getButtonLogout() {
        return buttonLogout;
    }

    public JButton getButtonMenuKamar() {
        return buttonMenuKamar;
    }

    public JButton getButtonSettings() {
        return buttonSettings;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBeranda = new javax.swing.JLabel();
        buttonMenuKamar = new javax.swing.JButton();
        buttonLihatCustomer = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonSettings = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelBeranda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelBeranda.setText("Beranda");

        buttonMenuKamar.setBackground(new java.awt.Color(58, 152, 248));
        buttonMenuKamar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMenuKamar.setForeground(new java.awt.Color(255, 255, 255));
        buttonMenuKamar.setText("Menu Kamar");
        buttonMenuKamar.setBorder(null);

        buttonLihatCustomer.setBackground(new java.awt.Color(58, 152, 248));
        buttonLihatCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLihatCustomer.setForeground(new java.awt.Color(255, 255, 255));
        buttonLihatCustomer.setText("Lihat Customer");
        buttonLihatCustomer.setBorder(null);

        buttonLogout.setBackground(new java.awt.Color(252, 104, 129));
        buttonLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(null);

        buttonSettings.setBackground(new java.awt.Color(58, 152, 248));
        buttonSettings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSettings.setForeground(new java.awt.Color(255, 255, 255));
        buttonSettings.setText("Settings");
        buttonSettings.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(labelBeranda))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonMenuKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(buttonLihatCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(labelBeranda)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMenuKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLihatCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLihatCustomer;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonMenuKamar;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JLabel labelBeranda;
    // End of variables declaration//GEN-END:variables
}
