/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import HotelReservationSystem.Customer;
import HotelReservationSystem.Database;
import HotelReservationSystem.DetilPemesanan;
import HotelReservationSystem.Hotel;
import HotelReservationSystem.Kamar;
import HotelReservationSystem.PilihanMenuKamar;
import HotelReservationSystem.TableHotel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JSpinner;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ASUS
 */
public class DetailHotel extends javax.swing.JPanel {

    private Kamar k;
    private String idHotel, idCustomer;
    private Database db;
    DefaultListModel<PilihanMenuKamar> listModelMenu;
    private ArrayList<Hotel> arrayExploreHotel;
    private boolean isChanging;
    /**
     * Creates new form DetailHotel
     */
    public DetailHotel() {
        initComponents();
        
        db = new Database();
        listModelMenu = new DefaultListModel<>();
        listKamar.setModel(listModelMenu);
        listKamar.addListSelectionListener(new DetailHotel.selectedMenuHandler());
    }
    
    public void setIdCustomer(String id_customer) {
        this.idCustomer = id_customer;
    }
    
    public void insertPemesanan() {
       int jumlahKamar = (int) SpinnerKamar.getValue();
       int jumlahMalam = (int) SpinnerMalam.getValue();
       
       Customer c = db.getCustomerById(idCustomer);
       Hotel h = db.getHotelById(idHotel);
       
       DetilPemesanan detilPemesanan = new DetilPemesanan(c, h, k, jumlahKamar, jumlahMalam);
       db.insertDetilPemesanan(detilPemesanan);
    }
    
    public void getAllKamar(){        
        isChanging = true;
        listKamar.clearSelection();
        
        listModelMenu.removeAllElements();
        ArrayList<PilihanMenuKamar> menu = db.getPilihanMenuByHotel(idHotel);
        for (PilihanMenuKamar p : menu)
            listModelMenu.addElement(p);
        isChanging = false;
    }
    
    private class selectedMenuHandler implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting() && !isChanging) {
                PilihanMenuKamar p = (PilihanMenuKamar) listKamar.getSelectedValue();
                k = p.getJenisKamar();
                LabelHargaKamar.setText(Integer.toString(p.getJenisKamar().getHargaPerMalam()));
                LabelBatasOrang.setText(Integer.toString(p.getJenisKamar().getBatasOrangPerKamar()));
                LabelKamarTersedia.setText(Integer.toString(p.getBanyakKamar()));
            }
        }
    }

    public void setIdHotel(String id_hotel) {
        this.idHotel = id_hotel;
    }
    
    public String getIdHotel() {
        return idHotel;
    }
    

    public JLabel getLabelBack() {
        return LabelBack;
    }

    public JSpinner getSpinnerKamar() {
        return SpinnerKamar;
    }

    public JSpinner getSpinnerMalam() {
        return SpinnerMalam;
    }

    public JButton getButtonPesan() {
        return ButtonPesan;
    }

    public JLabel getLabelHargaKamar() {
        return LabelHargaKamar;
    }

    public JLabel getLabelKamarTersedia() {
        return LabelBatasOrang;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelBack = new javax.swing.JLabel();
        ButtonPesan = new javax.swing.JButton();
        SpinnerKamar = new javax.swing.JSpinner();
        SpinnerMalam = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelHargaKamar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LabelBatasOrang = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKamar = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        LabelKamarTersedia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Detail Hotel");

        LabelBack.setForeground(new java.awt.Color(255, 51, 51));
        LabelBack.setText("< Back");

        ButtonPesan.setBackground(new java.awt.Color(58, 152, 248));
        ButtonPesan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonPesan.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPesan.setText("Pesan");

        jLabel3.setText("Jumlah Kamar");

        jLabel4.setText("Jumlah Malam");

        jLabel5.setText("Harga");

        jLabel6.setText("/kamar");

        LabelHargaKamar.setText(" ");

        jLabel8.setText("Batas orang");

        LabelBatasOrang.setText(" ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pesan kamar hotel sesuai keinginanmu");

        listKamar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(listKamar);

        jLabel9.setText("Kamar Tersedia");

        LabelKamarTersedia.setText(" ");

        jLabel7.setText("/malam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBack)
                .addGap(0, 837, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel9))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelHargaKamar)
                                    .addComponent(LabelKamarTersedia)
                                    .addComponent(LabelBatasOrang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(SpinnerMalam)
                            .addComponent(SpinnerKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerMalam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LabelHargaKamar)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(LabelBatasOrang)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(LabelKamarTersedia))
                        .addGap(77, 77, 77)
                        .addComponent(ButtonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPesan;
    private javax.swing.JLabel LabelBack;
    private javax.swing.JLabel LabelBatasOrang;
    private javax.swing.JLabel LabelHargaKamar;
    private javax.swing.JLabel LabelKamarTersedia;
    private javax.swing.JSpinner SpinnerKamar;
    private javax.swing.JSpinner SpinnerMalam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listKamar;
    // End of variables declaration//GEN-END:variables
}
