/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JLabel;

/**
 *
 * @author Muhammad Tsaqif Ammar
 */
public class MenuKamar extends javax.swing.JPanel {

    /**
     * Creates new form MenuKamar
     */
    public MenuKamar() {
        initComponents();
    }

    public JLabel getLabelBack() {
        return labelBack;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCustomer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKamar = new javax.swing.JList();
        labelTipe = new javax.swing.JLabel();
        textFieldTipe = new javax.swing.JTextField();
        labelHarga = new javax.swing.JLabel();
        textFieldHarga = new javax.swing.JTextField();
        labelBatasOrang = new javax.swing.JLabel();
        spinnerBatasOrang = new javax.swing.JSpinner();
        spinnerBanyakKamar = new javax.swing.JSpinner();
        labelBanyakKamar = new javax.swing.JLabel();
        buttonTambah = new javax.swing.JButton();
        buttonPerbarui = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        labelBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelCustomer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelCustomer.setText("Menu Kamar");

        listKamar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listKamar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listKamar);

        labelTipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTipe.setText("Nama Tipe");

        textFieldTipe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelHarga.setText("Harga Per Malam");

        textFieldHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelBatasOrang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBatasOrang.setText("Batas Orang Per Kamar");

        spinnerBatasOrang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        spinnerBanyakKamar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelBanyakKamar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBanyakKamar.setText("Banyak Kamar");

        buttonTambah.setBackground(new java.awt.Color(58, 152, 248));
        buttonTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("Tambah");
        buttonTambah.setBorder(null);

        buttonPerbarui.setBackground(new java.awt.Color(58, 152, 248));
        buttonPerbarui.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonPerbarui.setForeground(new java.awt.Color(255, 255, 255));
        buttonPerbarui.setText("Perbarui");
        buttonPerbarui.setBorder(null);

        buttonHapus.setBackground(new java.awt.Color(255, 51, 51));
        buttonHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setText("Hapus");
        buttonHapus.setBorder(null);

        labelBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelBack.setForeground(new java.awt.Color(255, 51, 51));
        labelBack.setText("< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelCustomer)
                        .addGap(11, 11, 11)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTipe)
                        .addGap(32, 32, 32)
                        .addComponent(textFieldTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelBatasOrang, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerBatasOrang, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelBanyakKamar)
                                .addGap(32, 32, 32)
                                .addComponent(spinnerBanyakKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(206, 206, 206))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipe)
                            .addComponent(textFieldTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHarga)
                            .addComponent(textFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerBatasOrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBatasOrang))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerBanyakKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBanyakKamar))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelBack)
                        .addGap(33, 33, 33)
                        .addComponent(labelCustomer)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonPerbarui;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelBanyakKamar;
    private javax.swing.JLabel labelBatasOrang;
    private javax.swing.JLabel labelCustomer;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelTipe;
    private javax.swing.JList listKamar;
    private javax.swing.JSpinner spinnerBanyakKamar;
    private javax.swing.JSpinner spinnerBatasOrang;
    private javax.swing.JTextField textFieldHarga;
    private javax.swing.JTextField textFieldTipe;
    // End of variables declaration//GEN-END:variables
}
